### ISSUE TITLE
No s̵u̵c̷h̷ ̸f̶i̷l̵e̷ ̵o̸r̴ ̷d̵i̴r̷e̵c̴t̵o̴r̵y̷ ̷s̶h̸

### ISSUE THREAD

**Issue by LanderN** [apierz/nerdbar.widget#4]
![schermafbeelding 2017-03-28 om 21 45 56](https://cloud.githubusercontent.com/assets/12765267/24424245/38ea53b4-1400-11e7-99ca-d35b6a0cd886.png)

What can I do to fix this? I cloned the repo with the command provided and installed the fonts. Python3 is installed by brew.

**Comment by apierz** [comment]
Sorry you are having trouble. I recently moved all my scripts to the same directory. It's working for me, but evidently others are having problems. Changing the shortcut to the absolute path for the script i.e.


`/Users/You/WidgetFolder/Scripts/mpd.sh`


instead of:

`./mpd.sh`


should fix the problem for now, but I will try and see if there's more I can do to make the paths more bullet proof.

I would also double check to make sure the scripts folder downloaded properly. Like I said I recently moved them around and might have screwed up a git add somewhere.
